compressionLevel: mixed

enableTelemetry: false

nodeLinker: node-modules

npmAlwaysAuth: false

npmScopes:
  arcgis:
    npmRegistryServer: "https://olympus.esri.com/artifactory/api/npm/npm-repo/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
